import {
  PACKAGE_ADDENDUM_ROOT,
  PACKAGE_BLOCK,
  PACKAGE_DATA_COMPACT,
  PACKAGE_FIELD,
  PACKAGE_FORM_GRID,
  PACKAGE_HINT,
  PACKAGE_SECTION_CARD,
  PACKAGE_SECTION_HEADER,
  PACKAGE_SECTION_TITLE,
  PACKAGE_SECTION_TITLE_MAIN,
  PACKAGE_TAB_COMPACT,
} from '../../../platform/ui/packageTabClassNames';

export const PRODUCT_ADDENDUM_TAB_COMPACT = PACKAGE_TAB_COMPACT;
export const PRODUCT_ADDENDUM_BLOCK = PACKAGE_BLOCK;
export const PRODUCT_ADDENDUM_DATA_COMPACT = PACKAGE_DATA_COMPACT;
export const PRODUCT_ADDENDUM_FORM_GRID = PACKAGE_FORM_GRID;
export const PRODUCT_ADDENDUM_SECTION_CARD = PACKAGE_SECTION_CARD;
export const PRODUCT_ADDENDUM_SECTION_HEADER = PACKAGE_SECTION_HEADER;
export const PRODUCT_ADDENDUM_SECTION_TITLE = PACKAGE_SECTION_TITLE;
export const PRODUCT_ADDENDUM_SECTION_TITLE_MAIN = PACKAGE_SECTION_TITLE_MAIN;
export const PRODUCT_ADDENDUM_FIELD = PACKAGE_FIELD;
export const PRODUCT_ADDENDUM_HINT = PACKAGE_HINT;
export const PRODUCT_ADDENDUM_ROOT = `${PACKAGE_ADDENDUM_ROOT}`;
