/** Иконки heroicons для категорий ремонта квартир (порядок — примерно по темам) */
export const SERVICE_ICON_OPTIONS = [
  { value: 'Home', label: 'Дом' },
  { value: 'HomeModern', label: 'Современный дом' },
  { value: 'BuildingOffice', label: 'Здание' },
  { value: 'BuildingOffice2', label: 'Здание 2' },
  { value: 'BuildingStorefront', label: 'Витрина / помещение' },
  { value: 'PaintBrush', label: 'Кисть / покраска' },
  { value: 'Swatch', label: 'Палитра / отделка' },
  { value: 'Square3Stack3D', label: 'Слои / материалы' },
  { value: 'RectangleStack', label: 'Плитка / панели' },
  { value: 'Squares2X2', label: 'Сетка / плитка' },
  { value: 'ViewColumns', label: 'Колонки / зоны' },
  { value: 'Cube', label: 'Объём / блок' },
  { value: 'WrenchScrewdriver', label: 'Инструменты' },
  { value: 'Wrench', label: 'Гаечный ключ' },
  { value: 'Bolt', label: 'Электрика' },
  { value: 'CpuChip', label: 'Слаботочка / умный дом' },
  { value: 'LightBulb', label: 'Освещение' },
  { value: 'Sun', label: 'Свет / окружение' },
  { value: 'Fire', label: 'Отопление' },
  { value: 'Window', label: 'Окна' },
  { value: 'Sparkles', label: 'Чистота / финиш' },
  { value: 'Beaker', label: 'Смеси / химия' },
  { value: 'ArchiveBox', label: 'Склад / материалы' },
  { value: 'Truck', label: 'Доставка' },
  { value: 'MapPin', label: 'Адрес / объект' },
  { value: 'ClipboardDocumentList', label: 'Смета / список' },
  { value: 'DocumentText', label: 'Документы' },
  { value: 'Photo', label: 'Фото' },
  { value: 'Scissors', label: 'Подрезка / текстиль' },
  { value: 'SpeakerWave', label: 'Акустика' },
  { value: 'Tv', label: 'ТВ / мультимедиа' },
  { value: 'DevicePhoneMobile', label: 'Связь' },
  { value: 'Clock', label: 'Сроки' },
  { value: 'CalendarDays', label: 'График' },
  { value: 'Banknotes', label: 'Оплата' },
  { value: 'ShieldCheck', label: 'Гарантия' },
  { value: 'UserGroup', label: 'Бригада' },
  { value: 'AcademicCap', label: 'Консультация' },
  { value: 'ArrowsRightLeft', label: 'Перепланировка' },
  { value: 'ChartBar', label: 'Смета / аналитика' },
  { value: 'Cog6Tooth', label: 'Сервис / настройка' },
  { value: 'Funnel', label: 'Фильтр' },
  { value: 'Key', label: 'Ключ / доступ' },
  { value: 'GlobeAlt', label: 'Сеть / онлайн' },
  { value: 'AdjustmentsHorizontal', label: 'Регулировка' },
] as const;
