import {
  PACKAGE_BLOCK,
  PACKAGE_DATA_COMPACT,
  PACKAGE_FORM_GRID,
  PACKAGE_HINT,
  PACKAGE_SECTION_CARD,
  PACKAGE_SECTION_FIELDS,
  PACKAGE_SECTION_HEADER,
  PACKAGE_SECTION_TITLE,
  PACKAGE_SECTION_TITLE_MAIN,
  PACKAGE_TAB_COMPACT,
} from '../../ui/packageTabClassNames';
import attachStyles from './PackageEstimateAttach.module.css';

export const ESTIMATE_TAB_COMPACT = PACKAGE_TAB_COMPACT;
export const ESTIMATE_BLOCK = PACKAGE_BLOCK;
export const ESTIMATE_DATA_COMPACT = PACKAGE_DATA_COMPACT;
export const ESTIMATE_FORM_GRID = PACKAGE_FORM_GRID;
export const ESTIMATE_SECTION_CARD = PACKAGE_SECTION_CARD;
export const ESTIMATE_SECTION_FIELDS = PACKAGE_SECTION_FIELDS;
export const ESTIMATE_SECTION_HEADER = PACKAGE_SECTION_HEADER;
export const ESTIMATE_SECTION_TITLE = PACKAGE_SECTION_TITLE;
export const ESTIMATE_SECTION_TITLE_MAIN = PACKAGE_SECTION_TITLE_MAIN;
export const ESTIMATE_HINT = PACKAGE_HINT;
export const ESTIMATE_TAB_HINT = `${ESTIMATE_HINT} ${attachStyles.estimateTabHint}`;
