export const TABLE_HEADERS = [
  { key: 'contractNumber', title: '№ договора', width: '100px' },
  { key: 'contractDate', title: 'Дата заключения', width: '110px' },
  { key: 'deliveryDate', title: 'Дата сдачи', width: '110px' },
  { key: 'contractAmount', title: 'Стоимость договора (без дс)', width: '140px' },
  { key: 'ds1', title: 'дс 1', width: '80px' },
  { key: 'ds2', title: 'дс 2', width: '80px' },
  { key: 'ds3', title: 'дс 3', width: '80px' },
  { key: 'ds4', title: 'дс 4', width: '80px' },
  { key: 'ds5', title: 'дс 5', width: '80px' },
  { key: 'payment1', title: 'Оплата 1', width: '90px' },
  { key: 'payment2', title: 'Оплата 2', width: '90px' },
  { key: 'payment3', title: 'Оплата 3', width: '90px' },
  { key: 'payment4', title: 'Оплата 4', width: '90px' },
  { key: 'payment5', title: 'Оплата 5', width: '90px' },
  { key: 'payment6', title: 'Оплата 6', width: '90px' },
  { key: 'payment7', title: 'Оплата 7', width: '90px' },
  { key: 'salaryContract', title: 'з/п дог.', width: '90px' },
  { key: 'salaryDs', title: 'з/п дс', width: '90px' },
];
