import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowsRightLeftIcon,
  BanknotesIcon,
  BeakerIcon,
  BoltIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  CubeIcon,
  DevicePhoneMobileIcon,
  DocumentTextIcon,
  FireIcon,
  FunnelIcon,
  GlobeAltIcon,
  HomeIcon,
  HomeModernIcon,
  KeyIcon,
  LightBulbIcon,
  MapPinIcon,
  PaintBrushIcon,
  PhotoIcon,
  RectangleStackIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  Square3Stack3DIcon,
  Squares2X2Icon,
  SunIcon,
  SwatchIcon,
  TruckIcon,
  TvIcon,
  UserGroupIcon,
  ViewColumnsIcon,
  WindowIcon,
  WrenchIcon,
  WrenchScrewdriverIcon,
} from '@heroicons/react/24/outline';

import type { ComponentType } from 'react';

/** Маппинг имён heroicons (как в БД) на React-компоненты */
export const serviceCatalogIconMap: Record<string, ComponentType<{ className?: string }>> = {
  AcademicCap: AcademicCapIcon,
  AdjustmentsHorizontal: AdjustmentsHorizontalIcon,
  ArchiveBox: ArchiveBoxIcon,
  ArrowsRightLeft: ArrowsRightLeftIcon,
  Banknotes: BanknotesIcon,
  Beaker: BeakerIcon,
  Bolt: BoltIcon,
  BuildingOffice: BuildingOfficeIcon,
  BuildingOffice2: BuildingOffice2Icon,
  BuildingStorefront: BuildingStorefrontIcon,
  CalendarDays: CalendarDaysIcon,
  ChartBar: ChartBarIcon,
  ClipboardDocumentList: ClipboardDocumentListIcon,
  Clock: ClockIcon,
  Cog6Tooth: Cog6ToothIcon,
  CpuChip: CpuChipIcon,
  Cube: CubeIcon,
  DevicePhoneMobile: DevicePhoneMobileIcon,
  DocumentText: DocumentTextIcon,
  Fire: FireIcon,
  Funnel: FunnelIcon,
  GlobeAlt: GlobeAltIcon,
  Home: HomeIcon,
  HomeModern: HomeModernIcon,
  Key: KeyIcon,
  LightBulb: LightBulbIcon,
  MapPin: MapPinIcon,
  PaintBrush: PaintBrushIcon,
  Photo: PhotoIcon,
  RectangleStack: RectangleStackIcon,
  Scissors: ScissorsIcon,
  ShieldCheck: ShieldCheckIcon,
  Sparkles: SparklesIcon,
  SpeakerWave: SpeakerWaveIcon,
  Square3Stack3D: Square3Stack3DIcon,
  Squares2X2: Squares2X2Icon,
  Sun: SunIcon,
  Swatch: SwatchIcon,
  Truck: TruckIcon,
  Tv: TvIcon,
  UserGroup: UserGroupIcon,
  ViewColumns: ViewColumnsIcon,
  Window: WindowIcon,
  Wrench: WrenchIcon,
  WrenchScrewdriver: WrenchScrewdriverIcon,
};
